name: notify
description: Notify, organize your thoughts and ideas, plan a big event, simplify planning important moments in your life with the Notify app. Start taking notes on your phone with Notify. Simple, colorful and fast.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_staggered_grid_view: ^0.6.2
  intl: ^0.17.0
  notes_repository:
    path: packages/notes_repository
  path: ^1.8.1
  path_provider: ^2.0.11
  sqflite_notes_api:
    path: packages/sqflite_notes_api
  firebase_core: ^0.4.2+2
  font_awesome_flutter: ^10.3.0
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  mockingjay: ^0.3.0

flutter:
  generate: true
  uses-material-design: true
