name: notes_api
description: An abstract class and models for providing access to notes.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.6.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.0
  coverage: ^1.5.0
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.21.4
